# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mikke/OneDrive/Skrivebord/xadc_with_bram/adc.srcs/sources_1/bd/xadc_pl2ps/ip/xadc_pl2ps_blk_mem_gen_0_0/xadc_pl2ps_blk_mem_gen_0_0.xci
# IP: The module: 'xadc_pl2ps_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mikke/OneDrive/Skrivebord/xadc_with_bram/adc.srcs/sources_1/bd/xadc_pl2ps/ip/xadc_pl2ps_blk_mem_gen_0_0/xadc_pl2ps_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_pl2ps_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/mikke/OneDrive/Skrivebord/xadc_with_bram/adc.srcs/sources_1/bd/xadc_pl2ps/ip/xadc_pl2ps_blk_mem_gen_0_0/xadc_pl2ps_blk_mem_gen_0_0.xci
# IP: The module: 'xadc_pl2ps_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mikke/OneDrive/Skrivebord/xadc_with_bram/adc.srcs/sources_1/bd/xadc_pl2ps/ip/xadc_pl2ps_blk_mem_gen_0_0/xadc_pl2ps_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_pl2ps_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
