# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mathi/OneDrive/Dokumenter/7semester/RobotElectronics/adc/adc.srcs/sources_1/bd/xadc_pl2ps/ip/xadc_pl2ps_processing_system7_0_0/xadc_pl2ps_processing_system7_0_0.xci
# IP: The module: 'xadc_pl2ps_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mathi/OneDrive/Dokumenter/7semester/RobotElectronics/adc/adc.srcs/sources_1/bd/xadc_pl2ps/ip/xadc_pl2ps_processing_system7_0_0/xadc_pl2ps_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_pl2ps_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/mathi/OneDrive/Dokumenter/7semester/RobotElectronics/adc/adc.srcs/sources_1/bd/xadc_pl2ps/ip/xadc_pl2ps_processing_system7_0_0/xadc_pl2ps_processing_system7_0_0.xci
# IP: The module: 'xadc_pl2ps_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mathi/OneDrive/Dokumenter/7semester/RobotElectronics/adc/adc.srcs/sources_1/bd/xadc_pl2ps/ip/xadc_pl2ps_processing_system7_0_0/xadc_pl2ps_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_pl2ps_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
