# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pyng_z2_related_matrials/pynq-z2_v1.0.xdc

# XDC: new/constrfil.xdc

# Block Designs: bd/xadc_pl2ps/xadc_pl2ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps || ORIG_REF_NAME==xadc_pl2ps} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_processing_system7_0_0/xadc_pl2ps_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_processing_system7_0_0 || ORIG_REF_NAME==xadc_pl2ps_processing_system7_0_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_xadc_wiz_0_0/xadc_pl2ps_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_xadc_wiz_0_0 || ORIG_REF_NAME==xadc_pl2ps_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_ps7_0_axi_periph_0/xadc_pl2ps_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_ps7_0_axi_periph_0 || ORIG_REF_NAME==xadc_pl2ps_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_rst_ps7_0_100M_0/xadc_pl2ps_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_rst_ps7_0_100M_0 || ORIG_REF_NAME==xadc_pl2ps_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_axi_bram_ctrl_0_0/xadc_pl2ps_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_axi_bram_ctrl_0_0 || ORIG_REF_NAME==xadc_pl2ps_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_xlconstant_0_1/xadc_pl2ps_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_xlconstant_0_1 || ORIG_REF_NAME==xadc_pl2ps_xlconstant_0_1} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_blk_mem_gen_0_0/xadc_pl2ps_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_blk_mem_gen_0_0 || ORIG_REF_NAME==xadc_pl2ps_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_xlconstant_0_2/xadc_pl2ps_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_xlconstant_0_2 || ORIG_REF_NAME==xadc_pl2ps_xlconstant_0_2} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_xlconstant_0_3/xadc_pl2ps_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_xlconstant_0_3 || ORIG_REF_NAME==xadc_pl2ps_xlconstant_0_3} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_xbar_0/xadc_pl2ps_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_xbar_0 || ORIG_REF_NAME==xadc_pl2ps_xbar_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_constant31x0_Low_0/xadc_pl2ps_constant31x0_Low_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_constant31x0_Low_0 || ORIG_REF_NAME==xadc_pl2ps_constant31x0_Low_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_PS_info_3_bits_0_0/xadc_pl2ps_PS_info_3_bits_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_PS_info_3_bits_0_0 || ORIG_REF_NAME==xadc_pl2ps_PS_info_3_bits_0_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_OR_bit_0_0/xadc_pl2ps_OR_bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_OR_bit_0_0 || ORIG_REF_NAME==xadc_pl2ps_OR_bit_0_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_comparator_N_bit_0_0/xadc_pl2ps_comparator_N_bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_comparator_N_bit_0_0 || ORIG_REF_NAME==xadc_pl2ps_comparator_N_bit_0_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_counter_N_bit_0_0/xadc_pl2ps_counter_N_bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_counter_N_bit_0_0 || ORIG_REF_NAME==xadc_pl2ps_counter_N_bit_0_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_comparator_N_bit_0_1/xadc_pl2ps_comparator_N_bit_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_comparator_N_bit_0_1 || ORIG_REF_NAME==xadc_pl2ps_comparator_N_bit_0_1} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_xlconstant_0_4/xadc_pl2ps_xlconstant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_xlconstant_0_4 || ORIG_REF_NAME==xadc_pl2ps_xlconstant_0_4} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_FrequencyConstant_0/xadc_pl2ps_FrequencyConstant_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_FrequencyConstant_0 || ORIG_REF_NAME==xadc_pl2ps_FrequencyConstant_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_FrequencyConstant_1/xadc_pl2ps_FrequencyConstant_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_FrequencyConstant_1 || ORIG_REF_NAME==xadc_pl2ps_FrequencyConstant_1} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_pwm_control_0_0/xadc_pl2ps_pwm_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_pwm_control_0_0 || ORIG_REF_NAME==xadc_pl2ps_pwm_control_0_0} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_auto_pc_1/xadc_pl2ps_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_auto_pc_1 || ORIG_REF_NAME==xadc_pl2ps_auto_pc_1} -quiet] -quiet

# IP: bd/xadc_pl2ps/ip/xadc_pl2ps_auto_pc_0/xadc_pl2ps_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_pl2ps_auto_pc_0 || ORIG_REF_NAME==xadc_pl2ps_auto_pc_0} -quiet] -quiet

# XDC: bd/xadc_pl2ps/xadc_pl2ps_ooc.xdc
